[package]
name = "deputy-package-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1"
deputy-library = { path = "../deputy-library", default-features = false }
semver = "1"

[features]
default = ["test"]
test = ["deputy-library/test"]
