host: localhost
port: 8080
repository:
  folder: /tmp/test-repo
  username: some-username
  email: some@email.com
storage_folders:
  package_folder: /tmp/packages
  toml_folder: /tmp/tomls
  readme_folder: /tmp/readme
database_url: mysql://mysql_user:mysql_pass@mariadb:3306/deputy
