[registries]
main-registry = { index = "http://10.80.60.167/git/index.git", api = "http://10.80.60.167:8080/" }

[package]
index_path = "/home/vscode/.deputy/index"
download_path = "/home/vscode/.deputy/download"
