[registries]
main-registry = { index = "http://127.0.0.1/git/index.git", api = "http://127.0.0.1:8080/" }

[package]
index_path = "/home/vscode/.deputy/index"
download_path = "/home/vscode/.deputy/download"
