host: 0.0.0.0
port: 8080
storage_folders:
  package_folder: /var/opt/deputy/deputy-package-server/package
  toml_folder: /var/opt/deputy/deputy-package-server/toml
  readme_folder: /var/opt/deputy/deputy-package-server/readme
