version: "3.7"

services:
  nginx-proxy:
    image: nexus.ocr.cr14.net:8003/nginx:latest
    restart: always
    ports:
      - "443:443"
      - "80:80"
    links:
      - deputy-package-server
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - deputy
    dns:
      - '10.81.50.8'
      - '10.81.50.9'

  deputy-frontend:
    image: nexus.ocr.cr14.net:8003/deputy-frontend:latest
    container_name: deputy-frontend
    networks:
      - deputy
    restart: unless-stopped

  deputy-package-server:
    image: nexus.ocr.cr14.net:8003/deputy-package-server:latest
    volumes:
      - ./config.yml:/var/opt/deputy/deputy-package-server/config.yml
      - ./deputy-package-toml:/var/opt/deputy/deputy-package-server/toml
      - ./deputy-package-readme:/var/opt/deputy/deputy-package-server/readme
      - ./deputy-packages:/var/opt/deputy/deputy-package-server/package
      - ./deputy-repository:/var/opt/deputy/deputy-package-server/repository
    container_name: deputy-package-server
    depends_on:
      - "deputy-mariadb"
    environment:
      - RUST_LOG=debug
    networks:
      - deputy
    restart: unless-stopped

  deputy-mariadb:
    image: nexus.ocr.cr14.net:8003/mariadb:10.7
    container_name: deputy-mariadb
    ports:
      - "3306:3306"
    volumes:
      - ~/deputy-mariadb:/var/lib/mysql
    networks:
      - deputy
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
      MYSQL_DATABASE: deputy

networks:
  deputy: {}
