import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button } from "@blueprintjs/core";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Button text="Click Me" />
      </main>

      <footer className={styles.footer}>
        <a>I&apos;m a footer</a>
      </footer>
    </div>
  );
};

export default Home;
