host: 0.0.0.0
port: 8080
repository:
  folder: /var/opt/deputy/deputy-package-server/repository
  username: deputy
  email: deputy@localhost
package_folder: /var/opt/deputy/deputy-package-server/package
