version: '3.7'

services:
  deputy-development:
    image: deputy-development
    build: ./deputy-development
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    user: vscode
    environment:
      - DATABASE_URL=mysql://mysql_user:mysql_pass@deputy-mariadb:3307/deputy

  deputy-package-server:
    image: nexus.ocr.cr14.net:8003/deputy-package-server:latest
    volumes:
      - ./deputy-packages:/var/opt/deputy/deputy-package-server/package
    environment:
      - RUST_LOG=debug

  deputy-mariadb:
    image: nexus.ocr.cr14.net:8003/mariadb:10.7
    ports:
      - "3307:3307"
    volumes:
      - ./deputy-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
      MYSQL_DATABASE: deputy
      MYSQL_TCP_PORT: 3307
