version: '3.7'

services:
  deputy-development:
    image: deputy-development
    build: ./deputy-development
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    user: vscode

  deputy-package-server:
    image: nexus.ocr.cr14.net:8003/deputy-package-server:latest
    volumes:
      - ./deputy-package-toml:/var/opt/deputy/deputy-package-server/toml
      - ./deputy-package-readme:/var/opt/deputy/deputy-package-server/readme
      - ./deputy-packages:/var/opt/deputy/deputy-package-server/package
      - ./deputy-repository:/var/opt/deputy/deputy-package-server/repository
    environment:
      - RUST_LOG=debug

  index-repository:
    image: nexus.ocr.cr14.net:8003/deputy-repository-server
    volumes:
      - ./deputy-repository/.git:/srv/git/index.git

  deputy-mariadb:
    image: nexus.ocr.cr14.net:8003/mariadb:10.7
    ports:
      - "3307:3307"
    volumes:
      - ~/apps/deputy-mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
      MYSQL_DATABASE: deputy
      MYSQL_TCP_PORT: 3307
