[package]
name = "deputy-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
git2 = "0.14"
insta = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
