[package]
name = "deputy-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.8.0"
anyhow = "1.0.56"
serial_test = "0.6.0"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
serde-aux = "*"
tempfile = "3"
semver = "1.0.6"

