[package]
name = "deputy-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
git2 = "0.14"
fancy-regex = "0.8"
insta = "1"
lazy_static = "1"
log = "0.4"
semver = "1"
toml = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
zip = { version = "0.6", features = ["bzip2"] }
zip-extensions = "0.6"
ignore = "0.4"

[features]
default = ["test"]
test = []
