[package]
name = "deputy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deputy-library = { path = "../deputy-library" }
fancy-regex = "0.8.0"
anyhow = "1.0.56"
serial_test = "0.6.0"
