[package]
name = "deputy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1"
clap = { version = "3", features = ["derive"] }
deputy-library = { path = "../deputy-library" }
reqwest = "0.11"
tempfile = "3"
toml = "0.5"
tokio = { version = "1.1", features = ["full"] }
