env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:@next/next/recommended
  - airbnb
  - airbnb-typescript
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
plugins:
  - react
rules:
  {
    'react/function-component-definition':
      [
        'error',
        {
          'namedComponents': 'arrow-function',
          'unnamedComponents': 'arrow-function',
        },
      ],
    'react/react-in-jsx-scope': 'off',
    react/jsx-props-no-spreading: 'off',
  }
