env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:@next/next/recommended
  - xo
overrides:
  - extends:
      - xo
      - xo-typescript
      - xo-typescript/space
    files:
      - "*.ts"
      - "*.tsx"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  {
    "react/react-in-jsx-scope": "off",
    "@typescript-eslint/indent": ["error", 2],
  }
