[package]
name = "deputy-package-server-routes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
deputy-library = { path = "../deputy-library" }
semver = "1"
